spring:
  application:
    name: web-gateway-service
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  sleuth:
    enabled: false
    sampler:
      probability: 1
  cloud:
    gateway:
      routes:
        ## USER-SERVICE
        - id: User-service
          uri: lb://User-service
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users**,/api/v1/admin/users/**

        ## USSD-HOLDINGS
        - id: hcp-web-core
          uri: lb://hcp-web-core
          predicates:
            - Path=/api/v1/payments/**,/api/v1/member/**,/api/v1/beneficiary/**

server:
  port: 6001

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:6000/eureka
#      defaultZone: http://registry-service:8761/eureka

security:
  oauth2:
    resource:
      id: holdings-web-service
    client:
      client-id: web-gateway-service
      client-secret: RobTheRich